enabled-worlds: ["world"]
min-y: 60
max-y: 320

trigger:
  on-chunk-load: true
  periodic-seconds: 0

exposure-neighbors: ["AIR", "WATER", "LAVA"]

preserve-natural:
  chests: true
  spawners: true

exclusions:
  categories:
    - LIQUIDS
    - GRAVITY
    - NON_FULL_BLOCKS
    - PLANTS
    - REDSTONE
    - CONTAINERS
    - PORTALS
    - SCULK_SENSORS
    - SCULK_SHRIEKER
  materials:
    - DRAGON_EGG
    - BUDDING_AMETHYST
    - REDSTONE_BLOCK
    - SNOW
    - BELL
    - END_ROD
    - LIGHTNING_ROD
    - IRON_BARS
    - JUKEBOX
    - NOTE_BLOCK

whitelist-overrides: []

tick-budget-ms: 2.0

log:
  changed-blocks: false

