name: BlockRandomizerReloaded
main: dev.konrad.brr.BlockRandomizerReloaded
version: 1.0.0
api-version: '1.19'
author: Konrad
commands:
  brr:
    description: Block Randomizer Reloaded admin commands
    usage: /brr <reload|dump>
    permission: brr.admin
permissions:
  brr.admin:
    default: op
