name: Build Plugin

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Java 17 (needed for Paper 1.19.2)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Validate Gradle installation
      - name: Verify Gradle
        run: gradle -v

      # Build the plugin JAR
      - name: Build with Gradle
        run: gradle build

      # Upload JAR artifact
      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v4
        with:
          name: block-randomizer-surface-optimized-jar
          path: build/libs/*.jar
