name: Build Plugin

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v4

      # Install Java 17 (Paper 1.19.2 requires Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Verify Gradle installation
      - name: Verify Gradle
        run: gradle -v

      # Build the plugin JAR
      - name: Build with Gradle
        run: gradle build

      # Upload the built jar to workflow artifacts
      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v4
        with:
          name: block-randomizer-reloaded-jar
          path: build/libs/*.jar
