name: build
on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8

      - name: Build
        run: gradle build --no-daemon

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: block-randomizer-reloaded-jar
          path: build/libs/*.jar
